# Generated by Django 6.0.6 on 2026-09-16 06:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerodrome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AerodromeStats',
            fields=[
                ('total', models.IntegerField(default=0)),
                ('id', models.IntegerField(default=1,
                 primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='aerodrome',
            name='icao_code',
            field=models.CharField(max_length=4, unique=True, validators=[
                                   django.core.validators.RegexValidator('^[A-Za-z]{4}$')]),
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(validators=[
                 django.core.validators.MinValueValidator(10)])),
                ('code', models.CharField(max_length=7)),
                ('aerodrome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='runways', to='aerodrome.aerodrome')),
            ],
            options={
                'unique_together': {('aerodrome', 'code')},
            },
        ),
    ]
