# Generated by Django 6.0.6 on 2026-07-07 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aerodrome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerodrome',
            name='icao_code',
            field=models.CharField(
                max_length=4,
                unique=True,
                validators=[django.core.validators.RegexValidator('^[A-Z]{4}$')],
            ),
        ),
    ]
