# Generated by Django 6.0.6 on 2026-07-07 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aerodrome', '0002_alter_aerodrome_icao_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerodrome',
            name='icao_code',
            field=models.CharField(
                max_length=4,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator('^[A-Za-z]{4}$')],
            ),
        ),
    ]
