# Generated by Django 6.0.6 on 2026-07-28 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aerodrome', '0003_alter_aerodrome_icao_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runway',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('len', models.IntegerField()),
                ('code', models.CharField(max_length=3)),
                (
                    'aerodrome',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='runways',
                        to='aerodrome.aerodrome',
                    ),
                ),
            ],
            options={
                'unique_together': {('aerodrome', 'code')},
            },
        ),
    ]
