# Generated by Django 6.0.6 on 2026-07-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aerodrome', '0004_runway'),
    ]

    operations = [
        migrations.CreateModel(
            name='AerodromeCounter',
            fields=[
                ('total', models.IntegerField()),
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
    ]
