# Generated by Django 6.0.6 on 2026-07-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerodrome', '0005_aerodromecounter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AerodromeCounter',
            new_name='AerodromeStats',
        ),
    ]
