# Generated by Django 6.0.6 on 2026-09-15 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerodrome', '0006_rename_aerodromecounter_aerodromestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerodromestats',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runway',
            name='length',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
